# Generated by Django 6.0.6 on 2026-09-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_questionfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionfile',
            name='complete',
        ),
    ]
