# Generated by Django 6.0.6 on 2026-07-27 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.CharField(max_length=300)),
                ('history_of_current_illness', models.TextField()),
                ('medical_history', models.TextField()),
                ('bp', models.CharField()),
                ('pulse', models.CharField()),
                ('temp', models.CharField()),
                ('oxygen_saturation', models.CharField()),
                ('diagnosis', models.TextField()),
                ('treatment_plan', models.TextField()),
                ('doctor_notes', models.TextField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment')),
            ],
        ),
    ]
