# Generated by Django 6.0.6 on 2026-08-18 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('instructions', models.TextField()),
                ('prescribed_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[], default='Active', max_length=20)),
                ('doctor_notes', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='appointments.appointment')),
            ],
        ),
    ]
